export const GET_BRANCH_LOADING = 'GET_BRANCH_LOADING';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const GET_BRANCH_FAILED = 'GET_BRANCH_FAILED';

export const GET_BRANCH_DETAIL_LOADING = 'GET_BRANCH_DETAIL_LOADING';
export const GET_BRANCH_DETAIL_SUCCESS = 'GET_BRANCH_DETAIL_SUCCESS';
export const GET_BRANCH_DETAIL_FAILED = 'GET_BRANCH_DETAIL_FAILED';
